#pragma once
#include <vector>
#include <algorithm>
#include <string>
#include <memory>
#include <iostream>
#include <fstream>
#include <sstream>
#include <map>
#include <stdlib.h>
#include "FileReader.h"
#include "FileWriter.h"